### ISSUE TITLE
Multiple engine instances parsing the same code throws exception

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#109]
Hi,

I am using Jurassic in unit tests, on dotnet core (it uses the `ReflectionEmitILGenerator`)
Each test has its own engine instance. But it seams that parsing twice the same script (loading a Promise polyfill) has an unexpected behavior :
`System.ArgumentException : Duplicate type name within an assembly`.
It happens [here](https://github.com/paulbartrum/jurassic/blob/master/Jurassic/Compiler/MethodGenerator/MethodGenerator.cs#L246).

I think it is because it reuses the same dynamic assembly in memory, thus having a conflicting class name.

**Comment by paulbartrum** [comment]
Does it still fail if you set `EnableDebugging` to false?

**Comment by MaitreDede** [comment]
Seams to work.

**Comment by paulbartrum** [comment]
Looks like the issue was a race condition. I've checked in a fix.

**Comment by MaitreDede** [comment]
Thanks, it works 👍
