### ISSUE TITLE
Large JS library compatibility

### ISSUE THREAD

**Issue by slothbag** [paulbartrum/jurassic#11]
I understand this can execute simple js scripts. Is it possible to run npm style modules? I have a lib that needs instantiating, and can then be used via numerous methods.. Some include Ajax or websocket usage behind the scenes executing call backs when done etc.

I can't figure out how to use it in Jurassic, i can't even get a reference to the instantiated object.

**Comment by paulbartrum** [comment]
Jurassic is purely a JS engine, based on the ECMAScript standard.  It doesn't support npm, AJAX or websockets, and I have no plans to add support for those features (ECMAScript 6 is the big focus right now).  Sorry!

**Comment by slothbag** [comment]
No worries, just trying to understand what I can use it for and what I cant.

So it sounds like I might be possible to replicate a browser environment by creating a C# method mapped into Jurassic called XmlHttpRequest.. then my purely ECMA script compatible JS script could call XmlHttpRequest and jump out to C# under the hood?

I got stuck just trying to instantiate a JS class from C#.. how would I instantiate this JS object and call its "doStuff" method from C#?

```
var MyClass = function() {
  this.doStuff = function() {
     console.log("It works");
  }
}
```

**Comment by paulbartrum** [comment]
Does this answer your question?
https://github.com/paulbartrum/jurassic/wiki/Exposing-a-.NET-class-to-JavaScript

**Comment by slothbag** [comment]
Yes, thankyou.
