### ISSUE TITLE
Question: Is it possible to expose a .NET object to JavaScript which has a method returning an IEnumerable?

### ISSUE THREAD

**Issue by AnotherSadGit** [paulbartrum/jurassic#116]
I'm trying to create a .NET class that will be exposed to JavaScript via Jurassic. The class represents an HTTP response object. Since an HTTP response may have multiple headers with the same name, I would like to include a method that returns an IEnumerable of the headers with a particular name.

This is what I have so far:

```C#
public class JsResponseInstance : ObjectInstance
{
    private IDictionary<string, IList<string>> _headers;

    public JsResponseInstance(ObjectInstance prototype)
        : base(prototype)
    {
        this.PopulateFunctions();
        _headers = new Dictionary<string, IList<string>>();
    }

    [JSFunction(Name = "addHeader")]
    public virtual void addHeader(string name, string value)
    {
        IList<string> vals;
        bool exists = _headers.TryGetValue(name, out vals);
        if (!exists)
        {
            vals = new List<string>();
            _headers[name] = vals;
        }
        vals.Add(value);
    }

    [JSFunction(Name = "getHeaders")]
    public virtual IList<string> getHeaders(string name)
    {
        IList<string> vals;
        bool exists = _headers.TryGetValue(name, out vals);
        if (!exists)
        {
            return new List<string>();
        }
        return vals;
    }
}
```
When I test the getHeaders method I get a JavascriptException: Unsupported type: System.Collections.Generic.IList'1[System.String]

I've tried changing the return type of the getHeaders method from IList to string[] and also adding the optional IsEnumerable property to the JSFunction attribute decorating the method. Neither change made a difference, I was still seeing the same exception.

Is there any way of returning an IEnumerable from a method in a .NET class that is exposed to JavaScript?

Cheers.

**Comment by paulbartrum** [comment]
You need to return something that inherits from `ObjectInstance`. For example:
```
    [JSFunction(Name = "getHeaders")]
    public virtual ArrayInstance getHeaders(string name)
    {
        IList<string> vals;
        bool exists = _headers.TryGetValue(name, out vals);
        if (!exists)
        {
            return ArrayConstructor.New();
        }
        return ArrayConstructor.New(vals.ToArray());
    }
```

**Comment by AnotherSadGit** [comment]
Thanks Paul.  I'll give it a shot later today.

**Comment by AnotherSadGit** [comment]
I've run into trouble.  I can't see a static New method in the ArrayConstructor class, only a New instance method.  I then tried 
```C#
return new ArrayConstructor();
```
instead of 
```C#
return ArrayConstructor.New();
```
but the constructor of the ArrayConstructor class is internal, so not accessible from my code.

I'm not sure how I should use the ArrayConstructor, given the lack of a public constructor or static methods.

**Comment by paulbartrum** [comment]
Oh sorry, it's accessible via the `ScriptEngine`.

```c#
scriptEngine.Array.New(...);
```

**Comment by AnotherSadGit** [comment]
Thanks, that did the trick.

For anyone else in a similar situation the working code is:
```C#
[JSFunction(Name = "getHeaders")]
        public virtual ArrayInstance getHeaders(string name)
        {
            IList<string> vals;
            bool exists = _headers.TryGetValue(name, out vals);
            if (!exists)
            {
                return this.Engine.Array.New();
            }
            return this.Engine.Array.New(vals.ToArray());
        }
```
