### ISSUE TITLE
EnableDebugging totally missing

### ISSUE THREAD

**Issue by thejonan** [paulbartrum/jurassic#119]
Currently all the code that is related to `ÈnableDebugging` functionality, along with corresponding symbolic information emitting is #ifdefed and not even compiling. Are there any plans in bringing back this functionality to live?

I was working on making the generated dynamic assembly fully debuggable in VS by improving the symbolic information being emitted, like reflecting the actual JS arguments, rather than internal `scriptEngine`, `scope` and `thisValue`. After some pause, I intend to resume these efforts, if that's still feasible in the Jurassic setup.

**Comment by paulbartrum** [comment]
EnableDebugging is problematic as it requires the use of `System.Reflection.Emit.TypeBuilder` to dynamically generate code, as opposed to `System.Reflection.Emit.DynamicMethod`. The latter is lighter, handles garbage collection properly, and is much simpler to code against. The only real downside of `DynamicMethod` is the lack of support for debug symbols. So when I migrated to .NET standard I focused on `DynamicMethod` and didn't bother attempting to support `TypeBuilder` (I put that functionality behind a flag, as you say).

I fixed the compile error when targeting .NET framework; thank you for reporting that.

Regarding the future of debugging support, I'm not too sure. Supporting .NET standard is much more important than debugging support, in my mind, and unfortunately there is no sign MS plans to support `System.Diagnostics.SymbolStore` in .NET standard.

**Comment by thejonan** [comment]
I've added some support for debugging, by wrapping the symbol generation process and providing a mechanism to have the Jurassic assembly user to provide an emitter capable of putting symbolic information. This way, both the Jurassic assembly stays .NET Standard 2.0 compatible, and a .NET Framework 4.6.1 compatible utilizing assembly can provide a symbolic aware emitter, in order to enable debugging. Refer to PR: #120 .

**Comment by paulbartrum** [comment]
Hopefully this issue is now addressed.
