### ISSUE TITLE
Date constructor error if date is 01-01-01 (precisly if year is before 970)

### ISSUE THREAD

**Issue by binish** [paulbartrum/jurassic#12]
`new ScriptEngine().Evaluate("new Date(new Date(969, 01, 01, 8, 17, 0)).getTime() == new Date(969, 01, 01, 8, 17, 0).getTime()")`  is **False**

`new ScriptEngine().Evaluate("new Date(new Date(970, 01, 01, 8, 17, 0)).getTime() == new Date(970, 01, 01, 8, 17, 0).getTime()")`  is **True**

**Comment by paulbartrum** [comment]
I tracked it down to this code in DateInstance.cs:
```
// Check if the milliseconds value is out of range.
if (double.IsNaN(milliseconds) || milliseconds < -31557600000000 || milliseconds > 31557600000000)
    return InvalidDate;
```

Unfortunately, I don't remember why that check is there!  The spec doesn't contain any reference to that number.

**Comment by paulbartrum** [comment]
I've checked in a fix.

**Comment by binish** [comment]
Thanks for the fix, Would there be release soon?

**Comment by paulbartrum** [comment]
I wasn't planning on doing a release any time soon, sorry!

Perhaps you could download the [v2.2](https://github.com/paulbartrum/jurassic/tree/v2.2) tag and then apply [the fix](https://github.com/paulbartrum/jurassic/commit/ff0d8ad218abdec02c237ce8fea79b859cf21424) manually?
