### ISSUE TITLE
Why some string functions are not working for me

### ISSUE THREAD

**Issue by DDAndyChen** [paulbartrum/jurassic#121]
"'To be, or not to be, that is the question.'.startsWith('To be')")

> TypeError: '\"To be, or not to be, that is the question.\".startsWith' is not a function"

String.raw('abc')

> TypeError: 'String.raw' is not a function"

'ab'.repeat(1)

> TypeError: '\"ab\".repeat' is not a function"

I see the these functions in unit test but not seem to work for me. However, functions like 'abc'.big(); 'abc'.anchor(); work

**Comment by paulbartrum** [comment]
Those functions are all quite new, are you using the NuGet package perhaps? I haven't updated that in quite some time.

**Comment by DDAndyChen** [comment]
@paulbartrum Yes, I'm using the NuGet package. Is there a plan to update the package soon?

**Comment by paulbartrum** [comment]
There's a whole bunch of stuff I want to get done before doing a v3.0 release (things like supporting promises). But maybe I can do a beta nuget package.

**Comment by DDAndyChen** [comment]
That would be an easier way to test the new features.

**Comment by paulbartrum** [comment]
I've uploaded a new package, make sure you've got "Show pre-release packages" to see it.

**Comment by paulbartrum** [comment]
I'm gonna assume the thumbs up means it solved your problem :-)

**Comment by DDAndyChen** [comment]
Thank you for your work!
