### ISSUE TITLE
Precedence of decrement operator

### ISSUE THREAD

**Issue by hulucc** [paulbartrum/jurassic#125]
The following code work fine in v8 engine but print NaN in Jurassic.Please Check.
```js
var xd = [1];
var yd = [1];
var i = 1;
xd[--i] = xd[i] + yd[i];
console.log(xd);
```

**Comment by LKI** [comment]
same here, please fix it

**Comment by hollow87** [comment]
I have an application that was forked 14 commits behind master and this works as expected.

**Comment by hulucc** [comment]
Nuget lastest stable 2.2.1
In order to support xp, I have to use the 2.x version :(

**Comment by hollow87** [comment]
That may be the issue as I just confirmed current master branch works as intended.

**Comment by paulbartrum** [comment]
This bug was reported and fixed more than a year ago. See https://github.com/paulbartrum/jurassic/issues/73 for details.

**Comment by paulbartrum** [comment]
I've created a v2.2.2 nuget package, just for you @hulucc :-)

**Comment by hulucc** [comment]
thank you !!!
