### ISSUE TITLE
Calling a function in a javascript library

### ISSUE THREAD

**Issue by thipages** [paulbartrum/jurassic#13]
Hi,
I want to call a function in an existing js library.
I did not find the way to do it

here is the library : http://turfjs.org/
As an example, I would like to call turf.distance from C#

Thank you

**Comment by paulbartrum** [comment]
You can use `scriptEngine.Execute("code")` or `scriptEngine.ExecuteFile("path")` to execute the javascript library code, then `scriptEngine.Evaluate("turf.distance()")` to run the distance function.

See https://github.com/paulbartrum/jurassic/wiki/Executing-a-script

**Comment by thipages** [comment]
Thank you for your quick feeback.
I tried the following code but it never ends (without writing on console).
I have put a break point after the Evaluate and it never reached it
I put null and null as arguments since they are complex objects

Do you think turf.min.js is not compatible with Jurassic?

```
           String path = @"js\turf.min.js";
           var engine = new Jurassic.ScriptEngine();
            try
            {
                engine.ExecuteFile(path); // executed
                engine.Evaluate("turf.distance(null,null)"); // never ends
                Console.WriteLine("ok");
            } catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
            }
            Console.WriteLine("done");
```

**Comment by thipages** [comment]
Sorry, the script after long time launches an exception : ReferenceError: javascript is not defined
This is due to the null, null arguments.

How can I pass elaborate objects as arguments?
For this function it requires the following object (http://turfjs.org/static/docs/module-turf_distance.html)
Thank you
```
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [-75.343, 39.984]
}
```

**Comment by paulbartrum** [comment]
Hmm, that does make it harder.  You need something like this (untested):

```c#
var param = engine.Object.Construct();
param["type"] = engine.Object.Construct();
var geometry = engine.Object.Construct();
geometry["type"] = "Point";
geometry["coordinates"] = engine.Array.New(new object[] { -75.343, 39.984 });
param["geometry"] = geometry;
((ObjectInstance)engine.Global["turf"]).CallMemberFunction("distance", param);
```

And yes, half a meg of javascript is going to be slow (everything gets compiled up front).  Sorry!

**Comment by thipages** [comment]
Hi,
First thank you for the syntax.
I try to put as it is required for the TURF libray (code below)
However I still got an exception : "ReferenceError: javascript is not defined"

Perhaps I am wrong with the  param1["properties"] which seems to be an empty (instanciated) object in the TURF library which seems to map with engine.Object.Construct()

What do you think?
Thank you.

```
           String path = @"js\turf.min.js";
            try
            {
                var engine = new Jurassic.ScriptEngine();
                engine.ExecuteFile(path);
                //
                var param1 = engine.Object.Construct();
                param1["type"] = "Feature";
                param1["properties"] = engine.Object.Construct();
                var geometry1 = engine.Object.Construct();
                geometry1["type"] = "Point";
                geometry1["coordinates"] = engine.Array.New(new object[] { 43.625, 3.61815 });
                param1["geometry"] = geometry1;
                //
                var param2 = engine.Object.Construct();
                param2["type"] = "Feature";
                param2["properties"] = engine.Object.Construct();
                var geometry2 = engine.Object.Construct();
                geometry2["type"] = "Point";
                geometry2["coordinates"] = engine.Array.New(new object[] { 43.6267, 3.60394 });
                param2["geometry"] = geometry2;
                //
                var res= ((ObjectInstance)engine.Global["turf"])
                                  .CallMemberFunction("distance",param1, param2);
                Console.WriteLine("ok");
            } catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
            }
            Console.WriteLine("done");
```

**Comment by paulbartrum** [comment]
The error indicates that the JS code is trying to use a variable called "javascript" which doesn't exist.  That doesn't seem like it's a problem with the parameters.  Potentially the script is trying to use a feature which is unsupported, or it could be a bug in Jurassic.  I'll take another look over the weekend.

**Comment by thipages** [comment]
Thank you.
If I can be of any help, tell me
Thierry

**Comment by paulbartrum** [comment]
Okay, the issue is that Turf has a dependency on a NPM module "javascript.util".

It runs correctly if I download the module (from [here](https://www.npmjs.com/package/javascript.util)) and use the following code:

```
var engine = new Jurassic.ScriptEngine();
engine.ExecuteFile(@"js\javascript.util.min.js");
engine.ExecuteFile(@"js\turf.min.js");
//
var param1 = engine.Object.Construct();
param1["type"] = "Feature";
param1["properties"] = engine.Object.Construct();
var geometry1 = engine.Object.Construct();
geometry1["type"] = "Point";
geometry1["coordinates"] = engine.Array.New(new object[] { 43.625, 3.61815 });
param1["geometry"] = geometry1;
//
var param2 = engine.Object.Construct();
param2["type"] = "Feature";
param2["properties"] = engine.Object.Construct();
var geometry2 = engine.Object.Construct();
geometry2["type"] = "Point";
geometry2["coordinates"] = engine.Array.New(new object[] { 43.6267, 3.60394 });
param2["geometry"] = geometry2;
//
var res = ((Jurassic.Library.ObjectInstance)engine.Global["turf"]).CallMemberFunction("distance", param1, param2);
Console.WriteLine(Jurassic.Library.JSONObject.Stringify(engine, res));
```

Notice that I'm running the `javascript.util.min.js` file before running the turf JS file.

**Comment by thipages** [comment]
Hi,
it works very well.
Script loading is a bit long, but this has to be once (my needs)
Thank you for your support and congratulation for your work.
Closed for me

**Comment by thipages** [comment]
Sorry, it is not totally closed.
I tried another function "along" I need
Find below the two object structure (the original javascript and a C# map, see bold parts)
I got the following "**Error: Coordinates must be an array**" on this call

```
// engine is wrapping Jurassic.engine (works well for distance function), no problem here
var middle12 = engine.along(geoPoints[0], geoPoints[1], geoPoints[2], geoPoints[3], 0.5);
(Jurassic.Library.ObjectInstance)engine.Global["turf"]).CallMemberFunction("along", segment12)
```

I guess I am wrong about the array structure in the code below
By the way, probably the same issue,  I did not understand your former map with new object[] {double1, double2} on distance function.

Thanks for helping me here

javascript
```
var line = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "LineString",
    "coordinates": [
**      [-77.031669, 38.878605],
      [-77.029609, 38.881946]**
    ]
  }
};
```

C#
```
        public ObjectInstance  segment (
             Double latitude1, Double longitude1,
            Double latitude2, Double longitude2)
        {
            var segment = engine.Object.Construct();
            segment["type"] = "Feature";
            segment["properties"] = engine.Object.Construct();
            var geometry = engine.Object.Construct();
            geometry["type"] = "LineString";
            geometry["coordinates"] = engine.Array.New(**new object[] {
                new object[] { latitude1, longitude1 },
                new object[] { latitude2, longitude2 }
            }**);
            segment["geometry"] = geometry;
            return segment;
        }
```

**Comment by paulbartrum** [comment]
Use `engine.Array.New` rather than `new object[]`.  So the C# code would be:

```
        public ObjectInstance  segment (
             Double latitude1, Double longitude1,
            Double latitude2, Double longitude2)
        {
            var segment = engine.Object.Construct();
            segment["type"] = "Feature";
            segment["properties"] = engine.Object.Construct();
            var geometry = engine.Object.Construct();
            geometry["type"] = "LineString";
            geometry["coordinates"] = engine.Array.New(
                engine.Array.New(latitude1, longitude1),
                engine.Array.New(latitude2, longitude2)
            );
            segment["geometry"] = geometry;
            return segment;
        }
```

**Comment by thipages** [comment]
Hi,
I prefer this way of constructing array.
Otherwise I got the same error: Jurassic.JavaScriptException with "Coordinates must be an array"
The mapping seems not to work for` geometry["coordinates"] `(below) 
If you could have a look
Thank you

```
[
      [latitude1, longitude1],
      [latitude2, longitude2]
]

engine.Array.Construct(
       engine.Array.Construct(latitude1, longitude1),
       engine.Array.Construct(latitude2, longitude2)
)
```

**Comment by paulbartrum** [comment]
I don't think that's the problem.  I think the problem is you're not passing in enough parameters to the `along` function.  It takes 3 parameters and in your earlier post you only pass in one parameter.

```
// engine is wrapping Jurassic.engine (works well for distance function), no problem here
var middle12 = engine.along(geoPoints[0], geoPoints[1], geoPoints[2], geoPoints[3], 0.5);
(Jurassic.Library.ObjectInstance)engine.Global["turf"]).CallMemberFunction("along", segment12, ***1, "miles"***)
```

**Comment by thipages** [comment]
Hi,

The last arguments is optional (by default miles)
I forgot another argument in the along function (distanceFrom1, see below). I aoplogize
I just run the script and it works.

I think I can manage the other functions of TURF library.
I thank you!!!!!

```
        public Object along(Double latitude1, Double longitude1, Double latitude2, Double longitude2, Double ratioFromPoint1,String unit="kilometers")
        {
            Double distanceFrom1 = distance(latitude1, longitude1, latitude2, longitude2) * ratioFromPoint1;
            ObjectInstance segment12 = segment(latitude1, longitude1, latitude2, longitude2);
            return ((Jurassic.Library.ObjectInstance)engine.Global["turf"]).CallMemberFunction("along", segment12, distanceFrom1, unit);
        }
```

**Comment by paulbartrum** [comment]
No problem :-)
