### ISSUE TITLE
Can I overload Operator of .NET class in JavaScript ?

### ISSUE THREAD

**Issue by Futahei** [paulbartrum/jurassic#130]
I create my original class for using in javascript.
And I want to use "+" , "-"
ex)
```
/* MyClass( index ) */
var a = new MyClass(50)
var b = new MyClass(100)

var c = a + b
console.log(c.index) // I want "150" but output is undefined
```

Can I overload operator like C# ?

**Comment by Futahei** [comment]
Add:)
`console.log(c)  //=> [object Object][object Object]

**Comment by paulbartrum** [comment]
Yes, you just need to override the valueOf() function, so that it returns the numeric value of the object.

Guide to how the addition operator works in javascript:
https://dmitripavlutin.com/javascriptss-addition-operator-demystified/

**Comment by Futahei** [comment]
ah, you mean that override ObjectInstance class's method, ValueOf() ?
```
[JSInternalFunction(Name = "valueOf")]
public ObjectInstance ValueOf()
{
  return this;
}
```

**Comment by paulbartrum** [comment]
That's the default implementation of valueOf(), which isn't virtual. But you can just redefine the valueOf() function in your class.

```c#
[JSInternalFunction(Name = "valueOf")]
public ObjectInstance ValueOf()
{
  return myNumericValue;
}
```

**Comment by Futahei** [comment]
OK. Thank you for your answer!
I'll try it.
