### ISSUE TITLE
How to run function?

### ISSUE THREAD

**Issue by NET-D3v3l0p3r** [paulbartrum/jurassic#136]
Hello,

firstly I want to thank you for your efforts.

Back to topic:
Is it possible to evaluate following script:
`function myFunction() { alert(\"Hello! I am an alert box!\");}` ?

I defined the function "alert" via 
  ```
    engine.SetGlobalFunction("alert", new Func<string, int>((p) =>
            {
                MessageBox.Show(p);
                return 1;
            }));

```

Executing the expression `alert(\"Hello World\");` works fine.

But when trying to evaluate the function the result is "undefined".
Is it possible to fix this somehow or extract the content of each function and executing then one by one?

Thanks in advance

**Comment by NET-D3v3l0p3r** [comment]
Okay got it:

```
   var engine = new Jurassic.ScriptEngine();
            engine.SetGlobalFunction("alert", new Func<string, int>((p) =>
            {
                Console.WriteLine(p);
                return 1;
            }));
 
            Console.WriteLine(engine.Evaluate("function myFunction() { alert(\"Hello! I am an alert box!\");}"));

            Console.WriteLine(engine.CallGlobalFunction("myFunction"));
            

```

**Comment by paulbartrum** [comment]
Glad to hear it's working :-)
