### ISSUE TITLE
ScriptEngine.ExecuteFile throws FormatException

### ISSUE THREAD

**Issue by Metalnem** [paulbartrum/jurassic#137]
**ScriptEngine.ExecuteFile** throws a **FormatException** when running the script from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
var engine = new ScriptEngine();
engine.ExecuteFile(path);
```

Found via [SharpFuzz].

[attached archive]: https://github.com/paulbartrum/jurassic/files/2707093/FormatException.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by paulbartrum** [comment]
I've checked in a fix for this, thanks!
