### ISSUE TITLE
ScriptEngine.ExecuteFile hangs permanently instead of throwing JavaScriptException

### ISSUE THREAD

**Issue by Metalnem** [paulbartrum/jurassic#138]
**ScriptEngine.ExecuteFile** sometimes hangs permanently instead of throwing **JavaScriptException** when encountering syntactically invalid JavaScript code. Here is the full program that reproduces such behavior:

```csharp
namespace Jurassic.Run
{
  public class Program
  {
    public static void Main(string[] args)
    {
      new ScriptEngine().Execute("for(a=0;a<2;a++[1])1");
    }
  }
}
```

Chrome and Safari display the following error when running this JavaScript snippet:

```SyntaxError: Unexpected token '['.```

Found via [SharpFuzz](https://github.com/Metalnem/sharpfuzz).

**Comment by paulbartrum** [comment]
The issue here is not that the loop hangs, it's that `a++[1]` doesn't produce a syntax error (it should).

**Comment by paulbartrum** [comment]
A good catch, thanks!
