### ISSUE TITLE
Creating a JavaScript object from .NET code

### ISSUE THREAD

**Issue by CPardi** [paulbartrum/jurassic#14]
Hi, I see from [here](https://github.com/paulbartrum/jurassic/wiki/Supported-types) that I can pass a `Jurassic.Library.ObjectInstance` (or a derived type) through the `.SetGlobalValue` method to create a Javascript Object. However, using Jurassic 2.1.0 from NuGet I see that the constructor for `ObjectInstance` is protected.

Would you be able to give me (or a link to) a quick example of creating an `ObjectInstance` with a property? Cheers.

**Comment by paulbartrum** [comment]
Obviously I need a help page on this! :-)

Here's some sample code:
```c#
var segment = engine.Object.Construct();
segment["type"] = "Feature";
segment["properties"] = engine.Object.Construct();
var geometry = engine.Object.Construct();
geometry["type"] = "LineString";
geometry["coordinates"] = engine.Array.Construct(
  engine.Array.Construct(-37.3, 121.5),
  engine.Array.Construct(-38.1, 122.6)
);
segment["geometry"] = geometry;
```

This is equivalent to the following javascript:
```javascript
var segment = {
  type: "Feature",
  properties: {},
  geometry: {
    type: "LineString",
    coordinates: [
      [ -37.3, 121.5 ],
      [ -38.1, 122.6 ]
    ]
  }
}
```

A warning with `engine.Array.Construct()`: it doesn't work as you may expect if you pass in only one argument.

**Comment by CPardi** [comment]
Hi, thanks for the answer it make perfect sense now. I have to say the syntax is really nice for this, really concise. I think a help page would be useful, using example above would probably make the situation clear enough.

I have a quick follow on question. How would I create a function property using a C# delegate? I have looked at `engine.Function.Construct()` but this doesn't seem to be the correct method. I am after something similar to `engine.SetGlobalFunction`, but for setting a property as a function.

Cheers

**Comment by paulbartrum** [comment]
Oh um, yeah... there unfortunately isn't a clean way to do this :-/

Here's a kind of hacky way to do it:
```c#
engine.SetGlobalFunction("temp123", ... your delegate ...);
var myFunc = (Jurassic.Library.FunctionInstance)engine.Global["temp123"];
// Optional clean up
engine.Global.Delete("temp123", throwOnError: false);
```

I plan to revamp how this works in the next major version (v3.0).

**Comment by CPardi** [comment]
I will use that method. Thanks for your help.
