### ISSUE TITLE
ScriptEngine.Execute throws some unexpected exceptions

### ISSUE THREAD

**Issue by Metalnem** [paulbartrum/jurassic#142]
**ScriptEngine.Execute** can throw many unexpected exceptions. Here are the types of exceptions it can throw and the code snippets used to trigger them:

#### ArgumentException

```csharp
new ScriptEngine().Execute("if(5 .toString(3)==0)(0)");
```

#### ArgumentOutOfRangeException

```csharp
new ScriptEngine().Execute("new Date(0,0)");
```

#### IndexOutOfRangeException

```csharp
new ScriptEngine().Execute("delete[].(0)");
```

#### InvalidCastException

```csharp
new ScriptEngine().Execute("({[0](");
```

#### NullReferenceException

```csharp
new ScriptEngine().Execute("function a(){for(a=0;a<0;0++)0}");
```

Found via [SharpFuzz](https://github.com/Metalnem/sharpfuzz).

**Comment by paulbartrum** [comment]
These should all now be fixed.
