### ISSUE TITLE
Exception in a while containing  switch

### ISSUE THREAD

**Issue by objmalloc** [paulbartrum/jurassic#144]
Hi, an `Jurassic.JavaScriptException: 'TypeError: undefined cannot be converted to an object'` is thrown when the following code is executed:

```javascript
function geoCode1() {
    while (true) {
        switch ("OK") {
            case "OK1":
                var result = [];
                break;
            //case "OK":
            //    break;

            //default:
            //    break;
        }
    }
};

geoCode1();
```

When debugging the exception is shown on the line with `break`. Actually it happens on a closing bracket of a `while` loop. Checked this by putting log before the closing bracket.

Look like the Exception is connected with optimization in a `LoopStatement`. When I comment `LoopStatement` code contained in `if (optimizationInfo.OptimizeInferredTypes == true)`, the Exception is not thrown anymore and the code works as expected.

**Comment by paulbartrum** [comment]
I've done a fix for this (sorry for the delay!)

**Comment by objmalloc** [comment]
Many thanks!
