### ISSUE TITLE
Built-in JSON.parse doesn't like keys that start with "0"?

### ISSUE THREAD

**Issue by Tinister** [paulbartrum/jurassic#147]
var engine = new Jurassic.ScriptEngine();
    engine.Evaluate(@"function f() { var o = JSON.parse('{""01"":""Foo"",""id"":""Foo""}'); return JSON.stringify(o); }");
    Console.WriteLine(engine.CallGlobalFunction("f"));

returns `{"id":"Foo"}` (skips "01" key)

Keys that are numbers that don't start with 0 ("11") or alphanumeric keys that start with 0 ("0S") seem to work.

I understand that JSON properties such as "01" can be a code smell (i.e. `o[1]` won't work), but with this particular script it is enforcing padded strings for the hash lookups.

**Comment by paulbartrum** [comment]
I get `{"01":"Foo","id":"Foo"}` when I run your code. What version of Jurassic are you using?

**Comment by Tinister** [comment]
2.2.2 running on framework 4.7.2

**Comment by paulbartrum** [comment]
Likely this issue was fixed after that release. I'll look into doing a v2.2.3/v3.0 release ASAP.

**Comment by paulbartrum** [comment]
I just published a Nuget package for v3.0, can you try it and let me know if it solves your problem?

**Comment by Tinister** [comment]
Works great.  Thanks for the extremely prompt turnaround.
