### ISSUE TITLE
Crashes in Xamarin.Android

### ISSUE THREAD

**Issue by gwell** [paulbartrum/jurassic#148]
Xamarin.Android crashes on the following line in a release build:

`Debugger_Break = GetStaticMethod(typeof(System.Diagnostics.Debugger), "Break");`

Crashes with the message: 
`System.InvalidOperationException: The static method System.Diagnostics.Debugger.Break() does not exist.`

I see that `Debugger_Break` is unused. Could it be removed?

**Comment by paulbartrum** [comment]
Yes! I removed it.

(I think this was used by the JS `debugger` statement at one point, but I'm using a different method now.)
