### ISSUE TITLE
.NET 4.0 support

### ISSUE THREAD

**Issue by JamesB7** [paulbartrum/jurassic#157]
Hello,

I just want you to know, I was able to get Jurassic running on .NET 4.0 with only the tiniest change.

In ClrBinder,
`fromType = fromType.GenericTypeArguments[0];`
becomes
`fromType = Nullable.GetUnderlyingType(fromType);`

No other change was necessary. Please consider incorporating this. It means a lot to me that this works and I'm sure I'm not the only one.

On another note, I very much appreciate that you have made a sandboxable JavaScript environment instead of one that exposes the host environment. This makes all the difference to me. Thank you so much.

James

**Comment by paulbartrum** [comment]
Sure, I'm happy to make this change. Commit is f734c9600b67d64d3460094b51fff44c87cbb24b

Thanks for the kind words :-)
