### ISSUE TITLE
Problems with ObjectInstance returning reference to C# struct/class

### ISSUE THREAD

**Issue by VapidLinus** [paulbartrum/jurassic#16]
I am not sure if it is appropriate to ask questions here, please close if not.

I have a script as such:

```csharp
namespace ScriptAPI
{
	public struct SensorData
	{
		public float Distance;
		public string Tag;
	}

	public class Sensor : ObjectInstance
	{
		public readonly string Name;
		public SensorData Data { get; set; }

		public Sensor(ScriptEngine engine, string name)
			: base(engine)
		{
			PopulateFunctions();
			Name = name;
		}

		[JSFunction(Name = "GetData")]
		public SensorData GetData()
		{
			return Data;
		}
	}
}
```

The Sensor instance has a Data property that is set elsewhere in my C# code and is not meant to be accessible via Javascript, but rather the GetData() method should return the data. _(I also have a GetDistance and GetTag shortcut method but left those out for simplicity)_

This is the code I use to execute the Javascript:

```csharp
// Prepare script engine
engine = new ScriptEngine()
{
	EnableExposedClrTypes = true
};

// Data types for robot parts
engine.SetGlobalValue("SensorData", typeof(SensorData));

// Robot
engine.SetGlobalValue("robot", machine);

engine.Execute(Code);
```

The `code` variable is the Javascript code and the `machine` variable is another ObjectInstance that contains arrays of Sensor instances. As soon as I try to run some Javascript that run the GetData() method I get the following exception:

```
NotImplementedException: Unsupported type: ScriptAPI.SensorData
Jurassic.Compiler.PrimitiveTypeUtilities.ToPrimitiveType (System.Type) <IL 0x00104, 0x00631>
...
```

I am assuming this is related to the [Supported Types](https://github.com/paulbartrum/jurassic/wiki/Supported-types) section in the wiki, but I thought using `engine.SetGlobalValue("SensorData", typeof(SensorData));` would allow me to use the C# type. I've also tried changing SensorData from a struct to a class but there's no difference.

Is there something I'm missing that would allow me to work past this, or do I have to store it as separate variables inside Sensor instead of a container struct?

Thank you in advance!

**Comment by paulbartrum** [comment]
I don't recommend using `EnableExposedClrTypes` - it was never fully implemented.

Could you use something like this instead?
```
[JSFunction(Name = "GetData")]
public ObjectInstance GetJSData()
{
    var result = Engine.Object.Construct();
    result["Distance"] = 123.0;
    result["Tag"] = "blah";
    return result;
}
```

**Comment by VapidLinus** [comment]
Ah, yes. This works perfectly. I didn't realize this is a thing you could do. Maybe not mentioned in the Wiki or me being a dummy. Thank you very much!

On the topic of `EnableExposedClrTypes`, how bad is this? I currently use it to expose some of Unity's non-world APIs, such as their Math, Vector3, Quaternion classes etc. Is this something I will have to try to replace with my own classes before releasing anything or will it work for cases like those?

**Comment by paulbartrum** [comment]
It's not you being a dummy -- creating objects and arrays is something I've been meaning to document properly for a while.  `EnableExposedClrTypes` has a bunch of rough edges.  I'm not sure exactly what rough edge you hit -- did you try to use an arithmetic operator on `SensorData`?  I'm haven't decided whether to spend the time to make it work properly, or whether to remove it in the next major version (v3).  It certainly makes it easier to pass data back and forth, but there's a lot of things in c# that don't map well to JS and I don't want features that only work most of the time.  (I'm also considering ditching the [JSFunction] attributes, which are slow and inflexible.)

**Comment by paulbartrum** [comment]
I've created a doc page here: https://github.com/paulbartrum/jurassic/wiki/Creating-objects-and-arrays
