### ISSUE TITLE
Regex bug with line endings handling

### ISSUE THREAD

**Issue by RusKnyaz** [paulbartrum/jurassic#162]
Execute the code:
```javascript
var rheaders = /^(.*?):[ \t]*([^\r\n]*)$/mg;
var headersString = 'X-AspNetMvc-Version: 4.0\r\nX-Powered-By: ASP.NET\r\n\r\n';
var arr = []
while ( match = rheaders.exec( headersString ) ) { 
arr.push(match[1].toLowerCase());
arr.push(match[ 2 ]);
}
```
Expected:
arr is array of ["x-aspnetmvc-version", "4.0", "x-powered-by", "ASP.NET"]
Observed:
arr is empty.

**Comment by paulbartrum** [comment]
Looks like the issue is that in .NET the `$` character matches `\n`:
```c#
new Regex("^.*$", RegexOptions.Multiline).Matches("one\r\ntwo\r\n")[0].Value
// returns "one\r"
```

Whereas in javascript it matches `\r` or `\n`:
```js
'one\r\ntwo\r\n'.match(/^.*$/m)[0]
// returns "one"
```

**Comment by paulbartrum** [comment]
The workaround is to change your regular expression:
```js
var rheaders = /^(.*?):[ \t]*([^\r\n]*)\r?$/mg;
```

**Comment by RusKnyaz** [comment]
Unfortunately I cannot use a workaround because this code is from jquery. And there are probably tons of code on web pages that use regular expressions. Please look at the similar issue in [jint](https://github.com/sebastienros/jint/pull/272#issuecomment-190528139)

**Comment by Taritsyn** [comment]
@RusKnyaz For implementation of regular expressions in the Jurassic, Jint and NiL.JS engines are used a `System.Text.RegularExpressions.Regex` class, which is not fully compatible with ECMAScript (see the [“Regular expression parsing error”](https://github.com/nilproject/NiL.JS/issues/160) issue).

**Comment by RusKnyaz** [comment]
@Taritsyn I kown it. And It is possible to fix. Please look the link I provided in previous comment.

**Comment by paulbartrum** [comment]
I've checked in a fix, let me know if it works for you :-)

**Comment by paulbartrum** [comment]
@RusKnyaz You'll notice that my fix is more complicated than the Jint one. It seems the fix in Jint is not correct.  `'one\r\ntwo'.match(/^.*$/mg).toString()` should return "one,,two" but in Jint it returns "one\r,two".

**Comment by kpreisser** [comment]
> @RusKnyaz You'll notice that my fix is more complicated than the Jint one. It seems the fix in Jint is not correct. `'one\r\ntwo'.match(/^.*$/mg).toString()` should return "one,,two" but in Jint it returns "one\r,two".

It seems the fix in Jurassic is also not 100% correct :wink:
E.g. `('one\\\r'.match(/^.*\\$/mg) || []).toString()` should return `one\` but returns an empty string.

**Comment by paulbartrum** [comment]
Ha, you're right, darn it.

**Comment by paulbartrum** [comment]
I checked in a fix for the escaping issue.
