### ISSUE TITLE
Unity3D mobile iOS/Android

### ISSUE THREAD

**Issue by agostta** [paulbartrum/jurassic#165]
Hi,
I have a question, is Jurassic working well to run small javascript codes in mobile games for iOS/Android wrote on Unity3D?

Thanks 👍

**Comment by paulbartrum** [comment]
I don't use Unity so I can't really comment, but I can say It's not designed for that purpose. I know a few people have managed to get Jurassic to work on Mono, with a few tweaks, so it is possible, but it's not likely to be easy. Sorry!
