### ISSUE TITLE
toFixed() adds leading zero

### ISSUE THREAD

**Issue by eaglemc** [paulbartrum/jurassic#167]
`(0.996).toFixed(2)` results in `"01.00"` instead of `"1.00"`
I don't understand everything going on in `NumberFormatter.ToString()`, but it looks like it adds a leading zero when it sees the number is less than one, but then the number gets rounded up and the leading zero should no longer be there.

**Comment by paulbartrum** [comment]
Thanks for the bug report, I've done a fix :-)
