### ISSUE TITLE
Xamarin.Forms System.PlatformNotSupportedException: 'Operation is not supported on this platform.'

### ISSUE THREAD

**Issue by Lelelo1** [paulbartrum/jurassic#169]
I get: 
> System.PlatformNotSupportedException: 'Operation is not supported on this platform.'

... trying to `engine.Evaluate(fileScript);` inside a Net Standard Library (2.0.3) from a Xamarin.Forms app.

The js file is set as `Embedded resource` in Visual Studio - following the answer given here: https://stackoverflow.com/questions/59154143/resources-in-net-standard-library-project/59177243#59177243

Where I have `fileScript` defined as so `static FileScriptSource fileScript = new FileScriptSource("index.js");`

What could be the problem?

**Comment by ackava** [comment]
On iOS Jurassic will not run, as you cannot emit IL and execute it. For iOS you can choose native JavaScriptCore offered by Apple. What I would recommend is create some interface and implement it for Android using Jurassic and on iOS using JavaScriptCore.

**Comment by Lelelo1** [comment]
@ackava 
Thank you for that information.

In my case I ultimately found to avoid needing to call js.
