### ISSUE TITLE
Debugger doesn't work

### ISSUE THREAD

**Issue by lhf552004** [paulbartrum/jurassic#172]
Hi, thanks, it's a great library, that's very useful.
But it cannot stop at the breakpoint (The line I set debugger).
Could you help to have a look?

### Version Info:
OS: win 10;
Visual Studio Professional 2017: 15.9.13
 .Net Framework: 4.6.1
Jurassic: 3.0.0

### C# Code:
```
 var engine = new Jurassic.ScriptEngine();
 engine.EnableDebugging = true;
 string path = Directory.GetCurrentDirectory();
 engine.ExecuteFile(Path.Combine(path, "getLunrIndexString.js"));
//selectedDocuments is an array of object
string documentsStr = JsonConvert.SerializeObject(selectedDocuments);
string lunrIndexString = engine.CallGlobalFunction<string>("getLunrIndexString", documentsStr);
```
### Javascript Code:
```
function getLunrIndexString(documentsStr){
    debugger;
    var documents = JSON.parse(documentsStr);
	var idx = lunr(function () {
        this.ref('id');
        this.field('label');
        this.field('content');

        documents.forEach(function (doc) {
            this.add(doc);
        }, this);
    });
    return JSON.stringify(idx);
}
```
By the way, it seems the parameter doen't pass into the function. Is there special js syntax for function?

**Comment by paulbartrum** [comment]
Make sure you run with the VS debugger active (i.e. not "Start without debugging").

I had to make some small modifications to the c# code to also execute "lunr.js", but after I did that it worked just fine. For me the resulting lunrIndexString was:
```
{"version":"2.3.8","fields":["label","content"],"fieldVectors":[["label/1",[]],["content/1",[]]],"invertedIndex":[],"pipeline":["stemmer"]}
```

**Comment by lhf552004** [comment]
Hi @paulbartrum , thanks for quick reply.
I think I have run in debug mode, (I run it with F5). Do you mean this?
It stop at CallGlobalFunction, although I don't set break point here.
Actually I hope it will stop in getLunrIndexString.js.
![image](https://user-images.githubusercontent.com/10030850/72583067-d6477c80-391f-11ea-9f07-babb6489d13f.png)

**Comment by paulbartrum** [comment]
If you do this:
1. Download the Jurassic source code from https://github.com/paulbartrum/jurassic
2. Open the solution Jurassic.sln in VS2019.
3. Right-click the project called "Debugger Test" and select "Debugger > Start new instance".

Does that stop on the debugger keyword (in the JS file) as expected?

**Comment by PoyangLiu** [comment]
@lhf552004, I had the same problem as you.  But I am able to step into the javascript after following @paulbartrum's instruction and the prime.js instruction to make sure debug option "Just My Code" is disabled.  See this StackOverflow link.
https://stackoverflow.com/questions/32048766/what-is-just-my-code.
