### ISSUE TITLE
How to pass in an array of arguments to a method through CallGlobalFunction?

### ISSUE THREAD

**Issue by threedaysmore** [paulbartrum/jurassic#174]
Some background: For better or worse, our app is built in a way where the same JavaScript needs to be executable on both Android and in C#.  Our setup on the C# side looks like this:

```
public class JurassicJavaScriptExecutor : IJavaScriptEngine
    {
        private ScriptEngine _engine;
        
        //constructor loads up the script that contains the methods we need executed
        public JurassicJavaScriptExecutor(string script)
        {
            _engine = new ScriptEngine();
            _engine.Evaluate(script);
        }
        public object ExecuteFunction(string functionName, object[] args)
        {
            object result;
            try
            {
                result = _engine.CallGlobalFunction(functionName, args);
            }
            catch (JavaScriptException e)
            {
                var msg = $"Parser Error executing Jurassic engine JavaScript function {functionName}() at line {e.LineNumber}: {e.GetAllMessages()}";
                throw new Exception(msg, e);
            }
            catch (Exception e)
            {
                var msg = $"Generic Error executing Jurassic engine JavaScript function {functionName}(): {e.GetAllMessages()}";
                throw new Exception(msg, e);
            }
            return result;
        }

        public void Dispose()
        {
            _engine = null;
        }
    }
```

When `result = _engine.CallGlobalFunction(functionName, args)` is called I get an System.ArgumentException about object conversion.

After some more digging it seems likely that I'm not passing `object[] args` in the correct way.

To simplify I've altered an [example ](https://github.com/paulbartrum/jurassic/wiki/Calling-a-JavaScript-function-from-.NET)from the Wiki

```
engine.Evaluate("function test(a, b) { return a + b }");
var args = new object[] {5,6};
**Console.WriteLine(engine.CallGlobalFunction<int>("test", args));**
```

Is there a way to achieve the last line in that code-block? I've used ints to stay in step with the example, but in our application it will be complex objects.

**Comment by paulbartrum** [comment]
The minimal example you provided works fine in my tests. My guess is you're passing in a value that has an unsupported type. Here is the list of supported types: https://github.com/paulbartrum/jurassic/wiki/Supported-types

Note that complex .NET objects are, in general, not supported, and cannot be passed to JS code "as-is". There are various ways around this, but it's hard to know what to recommend since I don't know what your objects look like.

**Comment by threedaysmore** [comment]
That makes sense.  Thanks for having a look, with it being a fairly complex object that I have little control over I'll attempt to solve this in another way.  I'll go ahead and close this.
