### ISSUE TITLE
Suggestion for object exchange between .net and Javascript

### ISSUE THREAD

**Issue by Sojaner** [paulbartrum/jurassic#18]
Hi,

First I wanted to thank you for the amazing work. Keep the great work going.

Next, I wanted to point you to a solution that I have been using for exchanging data between C# and Javascript.
While using ObjectInstance is theoretically the best practice in many situations, regarding the dynamic nature of the Javascript objects, most of the times the easiest way of exchanging data between C# and Javascript is a simple Json serialization.

While, I usually use Json.NET for doing so, but .net's builtin JavaScriptSerializer class also does an acceptable job.

This is just some idea for making things a little easier. Maybe it comes in handy in some situation.

Thanks for the great work.

**Comment by paulbartrum** [comment]
Yep, and there's a JSON serializer built into Jurassic, which (unlike Json.NET) serializes and deserializes Jurassic (JS) objects.  So if you have a .NET object you can serialize it to a string using Json.NET and then deserialize it to a Jurassic object using `JSONObject.Parse`.
