### ISSUE TITLE
EnableDebugging is gone from ScriptEngine

### ISSUE THREAD

**Issue by lhf552004** [paulbartrum/jurassic#184]
Just a question, is it debugging feature disabled?
As I found I cann't find it from ScriptEngine

Thanks

**Comment by paulbartrum** [comment]
It's disabled in .NET core, as, last I checked, this feature (emitting debugging symbols) wasn't supported in .NET core. It should still be present in the .NET 4.5 version of the library.

**Comment by paulbartrum** [comment]
Based on this doc page https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.marksequencepoint this is still the case.
