### ISSUE TITLE
Performance impacts between Managed objects and polyfill

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#19]
Hi,
I am using polyfills for some functions, and I wonder if there is a notable difference between a plain C# object and the polyfill.

Thanks.

**Comment by paulbartrum** [comment]
Performance varies wildly depending on what you are trying to do.  Time it and see :-)

**Comment by MaitreDede** [comment]
My question is because I added polyfill for glmatrix, typed arrays, and Promise... When I have time, I will try to hardcode polyfill and bench them...
