### ISSUE TITLE
Result of `JSON.stringify(99999.9999999999)` is `"099999.9999999999"`

### ISSUE THREAD

**Issue by lpa-vadim-zaslavsky** [paulbartrum/jurassic#193]
Related to #180 where the issue was partially fixed.

**Comment by paulbartrum** [comment]
How do you find these? lol

In my fix I'm now more consistently double-checking the Log10 result, which should resolve the issue for good. (I hope.)

**Comment by lpa-vadim-zaslavsky** [comment]
Thank you! The fix works great even with the negative numbers.
