### ISSUE TITLE
hi Jurassic.JavaScriptException' 형식의 예외가 Jurassic.dll에서 발생했습니다. ReferenceError: window is not defined

### ISSUE THREAD

**Issue by netilovefm1** [paulbartrum/jurassic#195]
I tried to jsp (window.function) 

but jurassic can't use window directly , are there any way to use jsp window func? 

Jurassic.JavaScriptException' 형식의 예외가 Jurassic.dll에서 발생했습니다.
ReferenceError: window is not defined

**Comment by paulbartrum** [comment]
Sorry, `window` refers to browser functionality and the intent of Jurassic is just to create a javascript engine, not an entire web browser. 🌐
