### ISSUE TITLE
ArrayBuffer and TypedArray access to internal buffer

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#20]
Hi,

Can it be possible to have direct access to internal byte[] buffer of TypedArrays in managed code ? So I can pass the buffer elsewhere without copying it.

Thanks

**Comment by paulbartrum** [comment]
Typed arrays are currently a work-in-progress, but I guess I have no problem exposing the byte buffer.

**Comment by MaitreDede** [comment]
Cool, thanks :)
I hope to see them soon, I am trying to mimic some brower functions, and I will need them. So I will test them :D
