### ISSUE TITLE
Return value of CompiledScript

### ISSUE THREAD

**Issue by hamarb123** [paulbartrum/jurassic#203]
Hi, I was wondering how I can get the return value of the evaluation of a `CompiledScript` class.
I noticed that it uses `GlobalMethodGenerator`, which supports a return value, but is internal, and its return value seems to just be discarded in the `CompiledScript.Execute(ScriptEngine engine)` method.
I was wondering if you could update the library to include variants of `Evaluate` in `CompiledScript` like in the `ScriptEngine` class since it seems like it would require no internal changes and seems like a logical extension to me.
The reason I want this is because I'm going to likely be evaluating the same script a lot of times in the same engine with possibly different global states, and want the return value, so rather than just calling `ScriptEngine.Evaluate(string)` every time, I'd like to cache the compilation.
Thank you!

**Comment by paulbartrum** [comment]
Depending on how old your version of the code is, there should be a `CompiledEval` class too. It's essentially identical to `CompiledScript` except it returns a value.

**Comment by hamarb123** [comment]
Thank you! I didn't see it since it doesn't have a method on `ScriptEngine` like `CompiledScript` does.

**Comment by hamarb123** [comment]
Hi, @paulbartrum, I'm using the Nuget package, and it doesn't seem to have a `CompiledEval` class.

**Comment by paulbartrum** [comment]
You're right; I uploaded a new version to Nuget for you (version 3.2) :-)

**Comment by hamarb123** [comment]
Thank you!
