### ISSUE TITLE
PropertyAccessorValue not visible

### ISSUE THREAD

**Issue by hamarb123** [paulbartrum/jurassic#205]
Hi, I was wanting to use the `PropertyAccessorValue` class in my code with `PropertyAttributes.IsAccessorProperty`, but it is not visible.
If it's not meant for public use, I won't use it, but I don't see any reason why not personally.
Thanks!

**Comment by paulbartrum** [comment]
If you want to see if a property is an accessor, use `obj.GetOwnPropertyDescriptor(key).IsAccessor`.
