### ISSUE TITLE
JSONObject.Parse() fails when number is in scientific notation

### ISSUE THREAD

**Issue by immitev** [paulbartrum/jurassic#208]
The code `JSONObject.Parse(new ScriptEngine(), @" {""E-notation"":-7E-05} "); ` fails with **"Invalid number."** exception

```
   at Jurassic.Library.JSONLexer.ReadNumericLiteral(Int32 firstChar)
   at Jurassic.Library.JSONParser.Consume()
   at Jurassic.Library.JSONParser.ParseObjectLiteral()
   at Jurassic.Library.JSONParser.ParseValue()
   at Jurassic.Library.JSONParser.Parse()
```

**Comment by paulbartrum** [comment]
Funny, that check for leading zeros in the exponent was put in very purposely, with unit tests and everything. No idea what I was thinking. Thanks for the bug report!

**Comment by alarkun** [comment]
Hi,

I am facing this issue, on version 3.2.4. 

Do you have plans to release a new stable version with this fix included?

Thanks a lot!

**Comment by paulbartrum** [comment]
I had no plans to do so, but ask and you shall receive :-) 3.2.5 is available now.

**Comment by alarkun** [comment]
Thanks a lot!! You are awesome
