### ISSUE TITLE
Threading and script compilation

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#21]
Hi,
I know that Engine is not thread safe, but I would like to know if I can call "Engine.Compile(ScriptSource)" in another thread, and then call "compiledScript.Execute()" on main thread without issues...
Thanks.

**Comment by paulbartrum** [comment]
Yes, that's fine.  The reason it's not thread-safe is just due to the lack of locking.  Either use your own locks, or just (as in this case) ensure that objects aren't accessed concurrently, and you won't have any problems.

**Comment by MaitreDede** [comment]
Yeah that is a good news ! So I can prepare scripts in parallel... I will give it a try...

**Comment by MaitreDede** [comment]
In my case, this is to serve a purpose of parallel loading of JS libs. For example, loading ThreeJs take some long seconds... So loading it in another thread let me use a "loading" script.
On the paper, compiling a script in another thread seams to work. I execute it only on main thread.
I will make a small benchmark to show diff.
