### ISSUE TITLE
JSON.stringify([].length) errors

### ISSUE THREAD

**Issue by lsim** [paulbartrum/jurassic#211]
Hi Paul

The error I get is

```
Unsupported value type: System.UInt32
```

This happens for any length of the array, by the way. 

It doesn't take much to get it working:

```
JSON.stringify([].length + 0);
```

**Comment by lsim** [comment]
Note that this is jurassic 2.1.0.0. It is quite possible that this is already fixed.

**Comment by paulbartrum** [comment]
It was indeed still an issue. I've committed a change to fix it. Thanks for the bug report!
