### ISSUE TITLE
JSONObject.Parse consumes more and more memory. Possible memory leak?

### ISSUE THREAD

**Issue by nekobul** [paulbartrum/jurassic#212]
`JSONObject.Parse` appears to consume more and more memory without GC appearing to release any memory.

Steps to reproduce:

1. Have on hand a rather large 2-3mb input JSON file.
2. Repeatedly read the JSON file and then assign to variable.
3. Assign the variable from step 3 to null and then call `GC.Collect()`.

Observerved behavior:

The used memory continues to increase. Explicitly requesting garbage collection has no effect.

Expected behavior:

The used memory by JS objects have to be reclaimed if there are no outstanding references.

**Comment by nekobul** [comment]
It appears the memory growth is related to the `HiddenClassSchema` use. Can you please provide more details what is the purpose of that class?

We are experimenting with the creation of a separate copies of that "schema" object for each new object and so far the memory growth appears to be tamed. However, we want to understand what is the technical reason for that class.

**Comment by nekobul** [comment]
I think we are starting to get closer to the issue. Each object is initialized with the following schema:

`this.schema = this.engine.EmptySchema;`

This leads to situation where instead of having an empty schema object, that object starts to overflow with all kind of objects being inserted for each created object in the engine. We are thinking that line should be changed to the following instead:

`this.schema = HiddenClassSchema.CreateEmptySchema();`

----

Still waiting for feedback from the creator.

**Comment by paulbartrum** [comment]
Sorry for the delay. The intention is that `HiddenClassSchema` describes the layout of an object, i.e. a list of property names and their attributes. Each unique object layout should have a single associated `HiddenClassSchema`, so the amount of memory should plateau after the first time you read the JSON file. Do you have a code snippet that can reproduce the problem? Otherwise I'll see if I can reproduce it on my end.

**Comment by paulbartrum** [comment]
I tried calling JSON.parse 1000x like this:
```
var engine = new ScriptEngine();
engine.SetGlobalValue("json", File.ReadAllText("events.json"));
engine.Execute(@"
    for (var i = 0; i < 10000; i ++)
        x = JSON.parse(json);
");
```
There were plenty of GCs but no increase in memory usage over time.

> this.schema = HiddenClassSchema.CreateEmptySchema();

This change would mean that `HiddenClassSchema` instances wouldn't be shared between objects, which would be very bad for memory usage in the general case. (But perhaps not in your particular case; I need to see exactly what you are doing to be sure.)

**Comment by nekobul** [comment]
Thank you for the explanation! The design you have described should be fine if there is no varience in terms of objects schema. However, if the objects schema is different and there are thousands of such different objects, the memory consumption goes completely out of control. We will try to prepare a test script for you to review, but I think you can easily reproduce the memory issue if you have objects with variable number of properties inside array.

**Comment by nekobul** [comment]
Please try the following script:

`
var propArray = [];

for (var i = 0; i < 100; i++)
	propArray.push("property" + i);

for (i = 0; i < 200000; i++) {
	var usedIndexes = [],
		testObj = {};

	for (var j = 0; j < 50; j++) {
		do {
			var propIdx = Math.floor(Math.random() * 100);
		} while (usedIndexes.indexOf(propIdx) > -1);

		usedIndexes.push(propIdx);

		testObj[propArray[propIdx]] = "test";
	}
}
`

That will show clearly the issue with the existing design. In our opinion, it makes sense to have a shared schema only if there is a good methodology to remove the elements from that shared schema dictionary after certain threshold. Otherwise, the memory grows to the point where it eventually runs out of memory.

**Comment by nekobul** [comment]
Posting further information and statistics from our tests below:

Shared schema:

Heap Size 2 228 419 KB

* HiddenClassSchema inclusive size 7 533 980 612 bytes, size 433 907 544 bytes, count 9 390 662

---

Not shared schema:

Heap Size 5 710 KB

* HiddenClassSchema inclusive size 307 444 bytes, size 80 500 bytes, count 1 322

---

50 instances of `HiddenClassSchema` size: 2 208 bytes. This is the amount of memory for the properties description of a single object.

The inclusive size of `ObjectInstance` is 5 592 bytes. All properties contain the value "test". 39% of object memory is taken by the properties description. This percent will decrease with the increase of size of property values. Now the value is small, just 8 bytes.

However, the heap increased just 120 MB compared to the shared schema. Also no use of such large arrays. Many objects can be created, but they are not kept forever in memory. In shared schema property transitions are never freed.

**Comment by paulbartrum** [comment]
Thanks for the example, it's very helpful. I think I can fix this by making the transitions weak references; that way `HiddenClassSchema` objects that are no longer in use by any objects can be freed by the GC.

**Comment by paulbartrum** [comment]
I've checked in a fix (9df93df). Are you able to confirm that it fixes your problem?

**Comment by nekobul** [comment]
Brilliant idea. Works very well. Thank you for all your hard work!!

**Comment by paulbartrum** [comment]
Great! I've published a new version of the NuGet package with this fix.
