### ISSUE TITLE
Catching script errors at compile time

### ISSUE THREAD

**Issue by themostdavid** [paulbartrum/jurassic#215]
Hi! I'm wondering if there's a way to catch errors in a script before actually running it. I'm using the CompiledScript.Compile() function to compile, and I was hoping I could use a try catch block to handle any typos or whatnot. This is so I can catch errors that are towards the end of scripts that take a long time to run. An example script:

```
for (...) // just a really long for loop
{...}

badFunc(); // I'd like to catch this undefined function error before running the script
```

Is this possible with Jurassic?

**Comment by paulbartrum** [comment]
Syntax errors will throw an exception when compiling -- but what you have there is specifically not a syntax error.

That's because the compiler doesn't (and can't) know if `badFunc` is undefined until it actually reaches that point in the execution.
```js
eval("badFunc = function() { }"); // <-- this eval can be in any function, and the string can be anything.
badFunc();  // <-- now works
```

**Comment by themostdavid** [comment]
I appreciate the answer, that makes sense. And thank you for developing this tool! It has saved me a lot of time.
