### ISSUE TITLE
PM - Customer side scripting for Channels

### ISSUE THREAD

**Issue by patrickvandersluis** [paulbartrum/jurassic#219]
Placeholder ticket - see https://github.com/paulbartrum/jurassic for project to embed JavaScript in C# code

**Comment by paulbartrum** [comment]
Please create issues only to report bugs or to suggest new features. If you want to save a repo for later, use GitHub's "star" functionality instead:
https://docs.github.com/en/get-started/exploring-projects-on-github/saving-repositories-with-stars
