### ISSUE TITLE
JsProperty, properties enumeration

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#22]
Hi,

I have followed the sample on [the wiki](https://github.com/paulbartrum/jurassic/wiki/Exposing-a-.NET-class-to-JavaScript#building-an-instance-class).

In the C# code, I create a new Constructor, then call ```Construct()``` to get an instance, that I expose with ```engine.SetGlobalValue("myobj", objInstance)```.

On my instance class, I have defined readonly properties :
```
        [JSProperty(Name = "console", IsConfigurable = false, IsEnumerable = true)]
        public ObjectInstance Console { get { return this.m_core.Console; } }
```
In this sample, the ```m_core``` variable is set in the constructor called by the ```Construct``` method.

When I run my script, when I try to read the property, the property is read from the prototype, not from the instance (the ```m_core``` variable is null).

[Test.zip](https://github.com/paulbartrum/jurassic/files/288769/Test.zip)

If I understand well, if I do a ```for(var prop in obj)```, when you make some checks against the property descriptor, but the downside is that it also retreive the property value, that in the case of the prototype is invalid/not readable.

What is the recommanded behavior : return ```null``` in case of the prototype ? or does it need a ScriptEngine modification ?

Thanks.

**Comment by paulbartrum** [comment]
I'll take a look next time I get a chance.

**Comment by MaitreDede** [comment]
:+1: I hope you are lucky ;)

**Comment by paulbartrum** [comment]
Thanks for the bug report -- I've done a fix :-)
