### ISSUE TITLE
Is it possible to go from JS to DLL and then to C# source?

### ISSUE THREAD

**Issue by tylike** [paulbartrum/jurassic#224]
Hi! 
In recent years, large language models have attracted great attention, but they mostly work in Python environment. However, I recently discovered a JavaScript alternative, https://github.com/xenova/transformers.js. Still, it is not my preferred C# language. Is it possible for me to compile them into DLL using Jurassic and then decompile them into C#?

thank you!

**Comment by paulbartrum** [comment]
Kind of... but not really. Jurassic converts JS into MSIL/CIL, which is then executed. There used to be support for saving the IL as a DLL, which you could then decompile back to C# using something like JetBrains DotPeek. However,
1) The support for saving emitted code to a DLL was removed in .NET core 1, and so I removed that functionality.
2) The C# which results is very far from idiomatic C#. In other words, it's barely readable. So it probably wouldn't help you much.

**Comment by tylike** [comment]
Yes, this task seems difficult to complete. I also tried wasm2cil, but it couldn’t even compile successfully.
