### ISSUE TITLE
How to run and use the Cheerio library or jsdom

### ISSUE THREAD

**Issue by sqlnew** [paulbartrum/jurassic#226]
I want to simulate a DOM environment without a browser on the backend server and use the JQuery library, so I want to use the Cheerio library or JSdom. May I ask how to use these JS libraries in the Jurassic environment? Thank you.

**Comment by paulbartrum** [comment]
In general you can use a JS library in Jurassic just by executing the script files. However, if it's intended for Node.JS then it may be using JS features Jurassic doesn't support. (Especially since I haven't updated this project in a while.)
