### ISSUE TITLE
Global variables overwritten from function call

### ISSUE THREAD

**Issue by objmalloc** [paulbartrum/jurassic#227]
When function created with new Function is called their parameters overwrite global variables. Can be reproduced with the following code.:

```csharp
var scriptEngine = new ScriptEngine();
var result = scriptEngine.Evaluate("a = 5;f = new Function('a', 'b', 'return a+b'); c = f(1, 3);a");
```

The value of the `result` is `1`, should be `5`.

**Comment by paulbartrum** [comment]
Good catch! I've published a fix here: [3.2.7](https://www.nuget.org/packages/Jurassic/3.2.7).
