### ISSUE TITLE
Change the Global object

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#23]
Hi,

I would like to know if I can replace the actual Global object with the one I have defined ?

I am thinking about the navigators ```window``` object, that is the ```this``` in global scope, and each ```window``` functions are available as global functions.

Thanks.

**Comment by paulbartrum** [comment]
You can modify the global object, but you can't replace it entirely.

Probably the way to do it is to instantiate a new instance of your global object, then transfer the functions across.

For example, to add the myfunction() function to the global object, do something like this (not tested):
```c#
var myObj = new MyGlobalObject(engine);
engine.Global["myfunction"] = myObj["myfunction"];
```
