### ISSUE TITLE
PopulateFunctions of inherited types

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#26]
Hi,

I have made a C# class inheritance for javascript object types :
```
ObjectInstance
+- MyBaseObject
    +- MyRealObject
    +- MyRealObject
```

The [Js*] attributes of ```MyBaseObject``` are not recognized by the ```PopulateFunctions()```, only the final type.

Is it possible to add a way to allow C# type inheritance for ObjectInstance derivation ?

Thanks.

**Comment by MaitreDede** [comment]
Solution :

In MyBaseObject, in prototype constructor :
```
this.PopulateFunctions(typeof(MyBaseObject));
```

In MyRealObject :
```
this.PopulateFunctions();
```

The PopulateFunction needs to be called at each type level, in each constructor called for object prototype.

**Comment by paulbartrum** [comment]
I'm actually considering removing `PopulateFunctions` and it's ilk in favour of a programmatic solution.  PopulateFunctions relies on reflection, which means it's slow, and the declarative syntax means it's inflexible.  There's no doubt it's also convenient, though.  TBD

**Comment by MaitreDede** [comment]
Cool :)

If you find a way to do things faster, this would be a great long-term benefit, especially for my project.

If possible, can you keep the attribute approach for exposing CLR objects to javascript, or something as easy ? Thanks.
