### ISSUE TITLE
External references?

### ISSUE THREAD

**Issue by HofMaus** [paulbartrum/jurassic#30]
I have a few unique issues while using Jurassic that have prompted me to ask, is there a way to perform some type of Include or reference within the JS source i am feeding in?

We know we could probably duck-tape it and simply append the script in at run-time but we are hoping to avoid skewing line numbers that way.

Is there already such support?

**Comment by paulbartrum** [comment]
The `ExecuteFile(path)` method on `ScriptEngine` is intended for just this scenario.  Are you trying to load the scripts from a file, or somewhere else?

**Comment by rodrigoroma** [comment]
You can not only call `ExecuteFile` but you can also call `Execute` twice to execute the library first and then to execute your code.

**Comment by HofMaus** [comment]
Those are both great ways to accomplish the task but not exactly what I am trying to target.  I have a shell written and when the user has the script entered in the GUI, the string is then executed (vs load from file).  In this instance, I need to execute once, include many by performing some type of nested include or something.

From the replies above, I take it there is not #include or anything like that.

**Comment by paulbartrum** [comment]
Ah, I get it.  Actually there is such a thing starting in ES6: the [import statement](https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import).  Unfortunately, Jurassic doesn't support it yet (and neither do any browser JS engines).

Instead, you could implement a global function to do this.  In JS it would look like this:
```
include("some identifier")
```

In .NET:
```
engine.SetGlobalFunction("include", new Action<string>(id => /* Load script and execute it */));
```
