### ISSUE TITLE
Question : Promise implementation

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#36]
Hi,

I would like to know if the "Promise" object will be implemented soon...

My implementation seams odd, and does not really work like expected in some cases.

I tried to rewrite and add it directly in Jurassic by trying to follow your design pattern, but reading the ECMA spec is not so easy : I wrote the skeleton (with NotImplementedException), and a way to handle promises that resolve after script execution, but some things remains complex...

My attempt is here : https://github.com/MaitreDede/jurassic/commits/promise

**Comment by paulbartrum** [comment]
Yes, Promises are definitely coming as part of the ES6 support.  However, Jurassic is all done in my spare time so I don't want to make any promises regarding the time-frame.
