### ISSUE TITLE
ArrayInstance.ParseArrayIndex() does not check if key is a canonical numeric String

### ISSUE THREAD

**Issue by T917820981726** [paulbartrum/jurassic#39]
Hi,
first of all, thank you for this great library. It is a good alternative to Jint due to the Javascript code being compiled instead of being interpreted.

It seems Jurassic has a similar bug that Jint had with detecting if a property name is a valid array index - see https://github.com/sebastienros/jint/issues/228.

Consider this Javascript code:
```javascript
var arr = ['A', 'B'];
console.log(arr['1'] === arr['001']);

arr['002'] = 'C';
console.log(arr.length);
```

If you run this code in Edge, Firefox, Chrome or Node.js, it will output:
```
false
2
```

However, on Jurassic (current master branch), it will output:
```
true
3
```

This seems to be caused by ArrayInstance.ParseArrayIndex() not correctly checking if key is a canonical numeric string (a "String representation of a Number that would be produced by ToString").

ECMAScript 2015 says at [6.1.7 (The Object Type)](http://www.ecma-international.org/ecma-262/6.0/#sec-object-type):
> An integer index is a String-valued property key that is a canonical numeric String (see 7.1.16) and whose numeric value is either +0 or a positive integer ≤ 2^53−1. An array index is an integer index whose numeric value i is in the range +0 ≤ i < 2^32−1.

[7.1.16 CanonicalNumericIndexString ( argument )](http://www.ecma-international.org/ecma-262/6.0/#sec-canonicalnumericindexstring):
> The abstract operation CanonicalNumericIndexString returns argument converted to a numeric value if it is a String representation of a Number that would be produced by ToString, or the string "-0".

[9.4.2 Array Exotic Objects](http://www.ecma-international.org/ecma-262/6.0/#sec-array-exotic-objects) (similar to [ECMAScript 5.1 at 15.4](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4)):
> NOTE: A String property name P is an array index if and only if ToString(ToUint32(P)) is equal to P and ToUint32(P) is not equal to 2^32−1.

This means that the string "002" shouldn't be a valid array index because
`ToString(ToUint32('002')) != '002'`.

Thank you!

**Comment by paulbartrum** [comment]
This is a great bug report, thanks!  I've checked in a fix :-)
