### ISSUE TITLE
JavaScriptExceptions are caught by foreign ScriptEngines

### ISSUE THREAD

**Issue by kpreisser** [paulbartrum/jurassic#45]
Hi,

as `ObjectInstance`s etc. have a reference to the `ScriptEngine` to which they belong, I assume one shouldn't take an ObjectInstance originating from one ScriptEngine and set it as property on another ScriptEngine. Is this correct?

In that case, I think the catch clauses for `JavaScriptExceptions` need to be adjusted. Currently, it is possible that one ScriptEngine throws a JavaScriptException, and if called recursively by another ScriptEngine, its JavaScript code may catch the exception. If that happens, it probably was unintended that a "foreign" JavaScriptException is catched in JS code.

We use Jurassic for extending an application with JavaScripts, where the transitions on the stack can be Native (.NET) -> JS (event handler or callback which calls a `FunctionInstance`), JS->Native (Script calls an API) and again Native -> JS (another callback).

Consider this simplified example:
EventProducer:

``` C#
        class EventProducer
        {
            public event Action MyEvent;

            protected void OnMyEvent() => MyEvent?.Invoke();

            public void Run()
            {
                // Run a script which raises the event.
                string script = @"
try {
    api.raiseEvent();
} catch (e) {
    console.log('e.myGlobalVariable: ' + e.myGlobalVariable);
}
";

                ScriptEngine engine = new ScriptEngine();
                //engine.Compile
                engine.ForceStrictMode = true;
                engine.SetGlobalValue("console", new FirebugConsole(engine));
                engine.SetGlobalValue("api", new Api(engine, this));
                engine.Execute(script);
            }


            private class Api : ObjectInstance
            {
                private EventProducer producer;

                public Api(ScriptEngine engine, EventProducer producer)
                    : base(engine)
                {
                    this.producer = producer;
                    PopulateFunctions();
                }

                [JSFunction(Name = "raiseEvent")]
                public void RaiseEvent()
                {
                    producer.OnMyEvent();
                }
            }
        }
```

EventConsumer:

``` c#
       class EventConsumer
        {
            private EventProducer producer;

            public EventConsumer(EventProducer producer)
            {
                this.producer = producer;
            }

            public void Run()
            {
                // Run a script which adds an event handler.
                string script = @"
var myGlobalVariable = 'Hi, this is a global variable.';

(function (globalObject) {
    api.addEventHandler(function () {
        // Throw the global object
        throw globalObject;
    });
})(this);
";

                ScriptEngine engine = new ScriptEngine();
                engine.ForceStrictMode = true;
                engine.SetGlobalValue("console", new FirebugConsole(engine));
                engine.SetGlobalValue("api", new Api(engine, this));
                engine.Execute(script);

            }


            private class Api : ObjectInstance
            {
                private EventConsumer consumer;

                public Api(ScriptEngine engine, EventConsumer consumer)
                    : base(engine)
                {
                    this.consumer = consumer;
                    PopulateFunctions();
                }

                [JSFunction(Name = "addEventHandler")]
                public void AddEventHandler(FunctionInstance instance)
                {
                    consumer.producer.MyEvent += () => instance.Call(null);
                }
            }
```

Main Program:

``` c#
            var producer = new EventProducer();
            var consumer = new EventConsumer(producer);

            consumer.Run();
            producer.Run();
```

In that example, `EventProducer` has a event which is raised by JS code. `EventConsumer` runs JS code which adds an event handler to the producer's event, and in that handler, throws a JS object.
Both EventConsumer and EventProducer may not know that each other will also run JS code. However, the JS code in the EventProducer can use a catch clause to catch the JavaScriptException and get access to a foreign ScriptEngine's objects (the global object in that case).

To change this, I think the clauses like `catch (JavaScriptException ex)` would need to be adjusted to `catch (JavaScriptException ex) when (ex.ScriptEngine == this.ScriptEngine)` or something similar, if this is possible (e.g. in the `TryCatchFinallyStatement` class, however I don't know how to do this correctly).

Thank you!

**Comment by paulbartrum** [comment]
> as ObjectInstances etc. have a reference to the ScriptEngine to which they belong, I assume one shouldn't take an ObjectInstance originating from one ScriptEngine and set it as property on another ScriptEngine. Is this correct?

Yes.

> To change this, I think the clauses like catch (JavaScriptException ex) would need to be adjusted to catch (JavaScriptException ex) when (ex.ScriptEngine == this.ScriptEngine) or something similar, if this is possible (e.g. in the TryCatchFinallyStatement class, however I don't know how to do this correctly).

Bit of a niche scenario, but I think you're right: that is probably the best solution.

**Comment by T917820981726** [comment]
Thanks!
I agree that this is not a common scenario. In our case we host different script engines (running different script code) that call API methods, in which case it is possible that two or more transitions from Native -> JS occur on the stack but use different ScripEngines. However we already catch all exceptions occuring in this steps, so it is currently not a problem for us.

**Comment by paulbartrum** [comment]
I've checked in a fix for this issue.
