### ISSUE TITLE
jquery support

### ISSUE THREAD

**Issue by whltd03** [paulbartrum/jurassic#49]
Is it Jquery supported?
For example if raw content of https://code.jquery.com/jquery-3.0.0.min.js is loaded and then additional custom functions which are using core Jquery function.
Should these functions work correct or no?

**Comment by paulbartrum** [comment]
No.  jQuery needs more than just a JavaScript environment -- it also assumes that a HTML document and DOM (document object model) is present.  While you could build a DOM-compatible object model on top of Jurassic, it would be a heck of a lot of work, and Jurassic does not attempt to do this.
