### ISSUE TITLE
Code generation build task

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#51]
Hi,

I would like if is possible to create a build task (that can be added to project with a nuget package) to add some code generation like your project "Attribute Code Generation" does, so javascript C# objects can be written correctly, according to Jurassic coding philosophy.

Thanks.

**Comment by paulbartrum** [comment]
Yes it's possible.  I haven't fully figured out how I want this to work yet.  I know I don't like the existing run-time method using reflection.  I'm still some way away from completing ES6 support, so we'll see how it pans out.
