### ISSUE TITLE
FileAPI support

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#52]
Hi,

I think it can be a good idea to add the FileAPI objects : https://www.w3.org/TR/FileAPI/

Maybe in a extension assembly (and nuget package) ?

**Comment by paulbartrum** [comment]
There's no reason why this couldn't be added, but I'm focused on ECMAScript 6 right now, so it's quite far down my list of priorities.  If you want to try implementing it yourself, let me know how you get on :-)
