### ISSUE TITLE
How will the Promise's onFulfilled handlers be implemented to be postponed until no script code is on the stack?

### ISSUE THREAD

**Issue by kpreisser** [paulbartrum/jurassic#54]
Hi,

I noticed you have started working on Promises, but did not yet implement handling the onFulfilled and onRejected handlers.
After reading through the Promises/A+ specification, I realized that these handlers are not invoked recursively, but instead postponed until no other script function is currently on the stack (which makes sense to avoid a StackOverflow when converting a loop to use promises).

For example. if you run:

``` javascript
console.log("1. Before resolve");
Promise.resolve(123).then(function() {
  console.log("2. Inside onResolved handler");
});
console.log("3. After resolve");
```

then the program prints:

```
1. Before resolve
3. After resolve
2. Inside onResolved handler
```

Do you have a thought of how to implement this so that the onFulfilled and onRejected handler's execution is postponed until no further script function is on the stack?

My thought was to have the ScriptEngine declaring a list of FunctionInstances that are to be invoked later, and a boolean that specifies if a function of this script engine is already on the stack:

``` c#
internal bool ScriptIsExecuting { get; set; }

internal List<FunctionInstance> ExecutionContextFunctionBuffer { get; } =
    new List<FunctionInstance>();
```

Then, maybe the FunctionInstance's `CallLateBound()` method could be changed to be not abstract but instead call an abstract `CallLateBoundCore()` function (and subclasses override the latter one instead of `CallLateBound()`), and the `CallLateBound()` can check if it needs to call the buffered function instances:

``` c#
public object CallLateBound(object thisObject, params object[] argumentValues)
{
    bool firstExecution = !Engine.ScriptIsExecuting;
    if (firstExecution)
        Engine.ScriptIsExecuting = true;

    try
    {
        var returnValue = CallLateBoundCore(thisObject, argumentValues);

        // Check if we are the first script function on the stack from this script engine
        // and we need to call buffered functions.
        if (firstExecution)
        {
            while (Engine.ExecutionContextFunctionBuffer.Count > 0)
            {
                List<FunctionInstance> copy =
                    new List<FunctionInstance>(Engine.ExecutionContextFunctionBuffer);
                Engine.ExecutionContextFunctionBuffer.Clear();

                foreach (var func in copy)
                    func.Call(Null.Value); // TODO

            }
        }

        return returnValue;
    }
    finally
    {
        if (firstExecution)
            Engine.ScriptIsExecuting = false;
    }
}
```

This way it would be ensured that if functions from multiple ScriptEngines are on the stack, the first function of each ScriptEngine on the stack will call the buffered FunctionInstances (this is currently how I do it in my code with a ES6-Promises Polyfill).

However, one issue is how to handle exceptions when FunctionInstances are buffered. For example, if you run this in Chrome:

``` javascript
Promise.resolve(123).then(function() {
  console.log("Inside onResolved handler");
});
throw new Error("My Error");
```

it will print on the console:

```
Inside onResolved handler
Uncaught Error: My Error(…)
```

So it will still call the onFulfilled handler and then throw the exception. This could be implemented by catching exceptions in the CallLateBound e.g. with `ExceptionDispatchInfo.Capture(ex)` to preserve the StackTrace when rethrowing it later, then running the buffered FunctionInstances and then rethrowing the exception. (I think the FunctionInstances shouldn't be run in a `finally` block as it marks a protected region of code and cannot be aborted with `Thread.Abort()`). 

Thanks!

**Comment by paulbartrum** [comment]
I was thinking that promise execution would happen at the `ScriptEngine` level, i.e. at the end of a `Execute`, `Evaluate` or `ExecuteFile`.  That avoids any problems with reentrancy and should be faster too (`FunctionInstance.Call`/`CallLateBound` is called a _lot_).

**Comment by MaitreDede** [comment]
Hi,

In my case, I have used a Promise polyfill. It relies on javascript methods "setImmediate" (or "setTimeout" with value of 0). But the function are evaluated in an other sequence. With your sample, instead of having "1 3 2" you would have "1 2 3", and the "then" functions are executed on the next loop iteration.

So to use Promise (and other stuff), I have done my own execution loop. First script execution executes the full script, and "while I have pending functions in the stack, tries to execute it". By "try to execute", I mean that a pending promise not resolved is stacked, but not executable (so kept on stack).
In the same maner, I have "setTimeout" and "cancelTimeout" (no need for setInterval yet).

This way, I expose Promises to do threaded operations (WinForms long initialization with UI libs, file loading...) and then, the promise "resolve" is called from other thread, but the "then" functions are called in main loop.

It is not the best solution, but we can say it works like in browsers.

**Comment by kpreisser** [comment]
Hi @paulbartrum,
thanks for your reply!

Running the scheduled Promise handlers at the `ScriptEngine` level is also what I first thought. However, when I want to run callbacks on the script later (after `Execute` has finished), I use the `FunctionInstance` supplied by the script code and then simply use `FunctionInstance.Call(...)`. But in this case, the promise handlers would still need to be called once this `Call` returns if this FunctionInstance resolves a promise.

(To clarify, before I run the Script code with `ScriptEngine.Execute(...)`, I set a global object with .NET methods where the Script can register events by supplying a callback, and the .NET method takes a `FunctionInstance` as parameter, which I save and then later `.Call()` to call back the script's handler. Is this the correct way?)

@MaitreDede Thanks! In our application we also provide e.g. a `setInterval` method to call back a `FunctionInstance` in a regular interval, and also to register for some internal events that can occur on any time. We also plan to provide an API that uses a `Promise` for long-running operations (e.g. reading a file), where we store the PromiseInstance internal and later call its `resolve` method, which then should call back the onFulfilled handlers. (The Callbacks will be called from a different thread than the one which called `ScriptEngine.Execute()`, but we ensure through locking that only one thread at a time calls a script function.

Thank you!
