### ISSUE TITLE
Support porting of Javascript to CSharp through Jurassic - feasible?

### ISSUE THREAD

**Issue by JimSEOW** [paulbartrum/jurassic#58]
Jurassic compile Javascript to IL, has anyone tried to convert the generated IL to cSharp? Currently I am evaluating if Jurassic could be used to support the porting of WebGL-based codes to C#. 

Step1 involves wrapping non-3D Canvas dependent javascript functions with Jarassic. This would allow testing of 3D canvas dependent codes in C#. 

Step2 (it would be great) if it is possible to compile non-3D canvas[ javascript codes to DLL.](https://github.com/paulbartrum/jurassic/issues/15) and reference the DLLs with C#

Step3 test the feasibility if the DLL could be converted to Csharp using tool like ILSpy. This would complete the complete porting from Javascript to C#.

Has anyone attempted? Could this be done? There are plenty of libraries support porting of Csharp to Javascript. There are hardly any robust Javascript to CSharp converter. Perhaps I am wrong.

**Comment by paulbartrum** [comment]
I've done this in the past, but the generated C# is pretty horrible.  Jurassic only does very basic type inference, so simple code like this:
```js
var x = y + z;
```
gets turned into something like this:
```c#
object x = TypeUtilities.Add(engine.Global["y"], engine.Global["z"]);
```

**Comment by JimSEOW** [comment]
@paulbartrum Thanks for replying. I am still trying to figure out the potential of Jurassic.
According to this [discussion](http://stackoverflow.com/questions/3757245/help-with-javascript-to-c-sharp-converter)

These are some of the options:
- [Javascript .NET](http://javascriptdotnet.codeplex.com/) : javascript to .NET dll but for old engine
- [Universal-transpiler](https://github.com/jarble/universal-transpiler): Javascript to c# (look-like-code) Not sure how good compared to [this](http://theantranch.com/blog/js-to-c-converter/)

I am continue the discussion, perhaps this could lead to a FAQ that is part of "What Jurassic is and is not? (with regards to Javacript to Csharp converter). Thanks again for your contribution.

**Comment by paulbartrum** [comment]
Jurassic is not a JS to C# converter.  It is a JS engine and runtime written in C#.  With some effort, you could use it to generate c# code from JS code, but without a lot of effort the generated code will be slow and ugly.

I recommend you instead use a tool which is designed for this purpose.  It sounds like "Universal transpiler" is your best bet.
