### ISSUE TITLE
Error message for incorrect "instanceof" operand always displays "undefined" as type

### ISSUE THREAD

**Issue by kpreisser** [paulbartrum/jurassic#59]
Hi,

I noticed the error message that occurs when using the `instanceof` operator with an non-function right side operand always displays `undefined` as its type.
For example:
```c#
    var engine = new ScriptEngine();
    try
    {
        engine.Execute("var x = ({} instanceof 123);");
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
```
displays:
```
TypeError: The instanceof operator expected a function, but found 'undefined' instead
```
instead of:
```
TypeError: The instanceof operator expected a function, but found 'number' instead
```

I think this is due to the following lines in [Compiler/Expressions/BinaryExpression.cs (line 716-720)](https://github.com/paulbartrum/jurassic/blob/5cc9c91eae98ffb47b8d4c5391a3e9fa6ec889fa/Jurassic/Compiler/Expressions/BinaryExpression.cs#L716):
```c#
            // Check the right-hand side is a function - if not, throw an exception.
            generator.IsInstance(typeof(Library.FunctionInstance));  // (1)
            generator.Duplicate();                                   // (2)
            var endOfTypeCheck = generator.CreateLabel();
            generator.BranchIfNotNull(endOfTypeCheck);
```

According to its documentation `generator.IsInstance` produces `null` when the object on the stack is not an instance of the specified type. The result is duplicated (I think for the `Branch` call), and in the error message branch the current stack value (`null`) is converted to `undefined`.

I think lines (1) and (2) need to be swapped, to retain the correct object on the stack for producing the error message.

Thanks!

**Comment by paulbartrum** [comment]
You're absolutely right -- thanks for taking the time to fix this :-)
