### ISSUE TITLE
MapInstance.Set() does not overwrite existing values

### ISSUE THREAD

**Issue by kpreisser** [paulbartrum/jurassic#63]
Hi,

when running the following code in Firefox, Chrome or other browsers:
```javascript
new Map().set(1, 2).set(0, 9).set(1, 8).get(1);
```
the return value is `8` (as `set(1, 8)` should overwrite the existing entry with value `2`).
However, on Jurassic it returns `2`.

`MapInstance.Set()` looks like the following:
```c#
    [JSInternalFunction(Name = "set")]
    public MapInstance Set(object key, object value)
    {
        if (this.store.ContainsKey(key))
            return this;
        if (key is double && TypeUtilities.IsNegativeZero((double)key))
            key = 0;
        var node = this.list.AddLast(new KeyValuePair<object, object>(key, value));
        this.store.Add(key, node);
        return this;
    }
```

So it checks whether the key already exists, but in that case does not set the new value.
ES2015 says at [23.1.3.9](http://www.ecma-international.org/ecma-262/6.0/#sec-map.prototype.set):
> 5. Repeat for each Record {[[key]], [[value]]} p that is an element of entries,
>    a. If p.[[key]] is not empty and SameValueZero(p.[[key]], key) is true, then
>        i. Set p.[[value]] to value.
>        ii. Return M.

So it seems the first `if` branch misses the code to set the new value.

Thanks!

**Comment by paulbartrum** [comment]
Fixed.
