### ISSUE TITLE
Unit tests failing due to computer culture

### ISSUE THREAD

**Issue by MaitreDede** [paulbartrum/jurassic#71]
Hi,

It seams that some unit tests are failing due to the computer current culture.

Example : in project `Unit Tests`, file `Library/NumberTests.cs`, for test `toLocaleString`, the second assert is failing :

```
            Assert.AreEqual("77.5", Evaluate("77.5.toLocaleString()"));
```
My computer current culture is `fr-fr` so the string for comparison should be "77**,**5".

What may be the best fix ? Culturize the comparison string ? Or set the culture to "InvariantCulture" for all the tests ?

**Comment by paulbartrum** [comment]
I fixed two failing tests (see the commit for details).  Let me know if there are any more.
