### ISSUE TITLE
Array.splice fails when no "deleteCount" parameter is specified

### ISSUE THREAD

**Issue by highfield** [paulbartrum/jurassic#72]
Accordingly to the specs, the "deleteCount" parameter is optional, and when it is not specified the array should be trimmed from the given starting point up to its end.
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

Here is my test snippet:
```
function func() {
    var res = {};
    var a = [0,1,2,3,4,5,6,7,8,9];
    res.before = JSON.stringify(a);

    a.splice(0, 2);
    res.then = JSON.stringify(a);

    a.splice(4);
    res.finally = JSON.stringify(a);

    return JSON.stringify(res);
}

```
Once tried on Jurassic leads this result:
`{"before":"[0,1,2,3,4,5,6,7,8,9]","then":"[2,3,4,5,6,7,8,9]","finally":"[2,3,4,5,6,7,8,9]"}`

However, by trying on any recent browser:
`{"before":"[0,1,2,3,4,5,6,7,8,9]","then":"[2,3,4,5,6,7,8,9]","finally":"[2,3,4,5]"}`

**Comment by highfield** [comment]
Well, I realized that the problem is not in this code, but in the confusion of the several implementations out there.
http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.splice
I tend to follow the Mozilla documentation as main reference. Should consider that unreliable, and favor ECMA as the only "Bible"?

**Comment by paulbartrum** [comment]
ECMA is the authoritative source, and if you look at the spec it says:

```
9. Else if the number of actual arguments is 1, then
  Let insertCount be 0.
  Let actualDeleteCount be len – actualStart.
```

Thus the spec is correct and Jurassic is wrong.  I've checked in a fix.  Thanks for reporting it :-)

**Comment by highfield** [comment]
Argh! you're right: I didn't realize what the pseudo-code write, but only the leading description. If you compare with the "slice" method, there the "undefined-as missing" is more clear.
Well, happy ending!
Many thanks
