### ISSUE TITLE
Target for .net 3.5

### ISSUE THREAD

**Issue by tiagobh** [paulbartrum/jurassic#76]
Hi, i´m trying build for .net 3.5 framework an it don´t work. What´s is the error?

it was not found "ConditionalWeakTable" in System.Runtime.CompilerServices;

` public partial class WeakMapInstance : ObjectInstance
    {
        private readonly ConditionalWeakTable<ObjectInstance, object> store;
`

Who to resolve this?

**Comment by paulbartrum** [comment]
I upgraded the project to .NET 4 so I could use `ConditionalWeakTable`.  To build on .NET 3.5 you'll have to comment out the `WeakMap` and `WeakSet` files.

**Comment by tiagobh** [comment]
Ok, Thank's. \o/
