### ISSUE TITLE
Catch javascript execute file errors with line numbers to string

### ISSUE THREAD

**Issue by AskingQuestions** [paulbartrum/jurassic#78]
I want to ExecuteFile(path) and get any errors that are produced by this file in a string format that shows a stack and line numbers.

Is there any way to do this?

**Comment by paulbartrum** [comment]
If there is an error, Jurassic will throw an exception of type `Jurassic.JavaScriptException`.  That class has the line number, source file path and executing function name.

**Comment by AskingQuestions** [comment]
Ok thanks, what about javascript try catch I tried and caught an error but it did not give me the line number.

**Comment by paulbartrum** [comment]
If you're catching the exception in the javascript code itself, then you can use the `stack` property.

```
function f() {
    throw new Error('sdfsdf');
}

try {
    f();
} catch (e) {
    console.log(e.stack);
}
```

Prints this:
```
 Error: sdfsdf
    at f (c:\temp\test.js:2)
    at c:\temp\test.js:6
```
