### ISSUE TITLE
NewExpression does not push a stack frame

### ISSUE THREAD

**Issue by kpreisser** [paulbartrum/jurassic#79]
Hi,

I noticed that when using the NewExpression ("new func()"), it does not push a stack frame on the ScriptEngine, while it does when calling the function directly.
```javascript
function doSomething() {
    try {
        throw new Error('Hi');
    } catch (e) {
        console.log(e.stack);
    }
}

doSomething();
```
Output:
```
 Error: Hi
    at doSomething (unknown:3)
    at unknown:9
```

When you change `doSomething();` to `new doSomething();`, the initial stack frame does not appear:
```
 Error: Hi
    at doSomething (unknown:3)
```

This seems to be because the `FunctionCallExpression` calls `FunctionInstance.CallWithStackTrace`, supplying the path, function and line. CallWithStackTrace then pushes a frame with that information and calls `FunctionInstance.CallLateBound()`.

However, `NewExpression` calls `ConstructLateBound` without those parameters. I think this can be solved by implementing a "ConstructWithStackTrace()" function similar to "CallWithStackTrace", and then using this function in the NewExpression.

**Comment by paulbartrum** [comment]
Thanks for this.  I modified your PR slightly to include "new" in the stack trace.
