### ISSUE TITLE
Social Media Updates?

### ISSUE THREAD

**Issue by Chamberlain91** [paulbartrum/jurassic#8]
This isn't an issue, so it can be closed as soon as you see this.
I just wasn't sure how else to message you about if there was a social media account to receive updates about Jurassic, or I just need to pop my head over here every once in a while.

**Comment by paulbartrum** [comment]
Sorry, that's a negative, I'm not a big believer in social media :-)  You might want to consider "watching" the repository if you want change notifications.

https://help.github.com/articles/watching-repositories/
