### ISSUE TITLE
How do I call a constructor?

### ISSUE THREAD

**Issue by niuk** [paulbartrum/jurassic#88]
I have some code that defines a simple vector class:
````
var Vector3 = (function () {
    function Vector3(x, y, z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
    return Vector3;
}());
````
How do I evaluate the equivalent of `new Vector(x, y, z)` via the C# API? I've tried `((FunctionInstance)scriptEngine.GetGlobalValue("Vector3")).ConstructLateBound(x, y, z);` but `ConstructLateBound` seems to take a single bool instead, so the only way I've managed to make a vector is by writing the following:
````
var v = ((FunctionInstance)scriptEngine.GetGlobalValue("Vector3")).ConstructLateBound(true); // I have no idea what the bool parameter does here
v.SetPropertyValue("x", x, true);
v.SetPropertyValue("y", y, true);
v.SetPropertyValue("z", z, true);
return v;
````

**Comment by paulbartrum** [comment]
`ConstructLateBound` doesn't take a bool... `ConstructLateBound(x, y, z)` should work fine.  Can you detail why this is not working for you?

**Comment by niuk** [comment]
The problem went away once I upgraded from version 2.2.1 (from NuGet) to the latest from this GitHub repository. `ConstructLateBound` works now. Thanks!

**Comment by paulbartrum** [comment]
Weird, I don't remember `ConstructLateBound` ever taking a bool, but oh well, I'm glad you got it to work :-)
