### ISSUE TITLE
setTimeout is not defined

### ISSUE THREAD

**Issue by hstarorg** [paulbartrum/jurassic#89]
When code has setTimeout, it throw an error.

**Comment by paulbartrum** [comment]
`setTimeout` is not part of the ECMAScript standard, and as such it's not part of Jurassic either.  Sorry!

It is possible to define the `setTimeout` function yourself (though not easy if you want to match the semantics precisely).  Check the wiki for how to do this.

**Comment by hstarorg** [comment]
Thanks, [https://github.com/frozenice/JurassicTools](https://github.com/frozenice/JurassicTools) help me fix it.
