### ISSUE TITLE
The " es5 " and " let " support good enough

### ISSUE THREAD

**Issue by zgsxtyzgd** [paulbartrum/jurassic#91]
for(let i=0;i<20;i++)
    .....
error:"SyntaxError: Unexpected token 'let' in expression."
And " let " keyword must be " Strict Mode " mode, obviously this is not necessary

**Comment by paulbartrum** [comment]
`Let` is new in ECMAScript 6.  There is a table showing which features of ECMAScript 6 are supported at the bottom of this page: https://github.com/paulbartrum/jurassic

**Comment by zgsxtyzgd** [comment]
Sorry． I made a mistake
