### ISSUE TITLE
Run as interpreter only?

### ISSUE THREAD

**Issue by kf-jstatz** [paulbartrum/jurassic#93]
We're currently porting a project that makes use of Jurassic to a platform which forbids  JIT compilation.  I haven't found any mention of this in the wiki, but know some other similar projects allow JIT to be disabled, so that the engine can run purely as an interpreter.  Is something like that possible for Jurassic?  I saw there were some flags for compatibility modes but they don't mention anything like this.

**Comment by paulbartrum** [comment]
Sorry, there's no interpreter in Jurassic.  It's compilation only.
